services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    env_file:
      - .env
    ports:
      - "8080:8080"
    command: ["java", "-jar", "/app/app.jar"]
