apiVersion: apps/v1
kind: Deployment
metadata:
  name: sp-demo-java-app
  labels:
    app: sp-demo-java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sp-demo-java-app
  template:
    metadata:
      labels:
        app: sp-demo-java-app
    spec:
      containers:
        - name: sp-demo-java-app
          image: us-central1-docker.pkg.dev/sp-demo-java-app/sp-demo-java-app-repo/sp-demo-java-app:tag-placeholder
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: SL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: sealights-secret
                  key: sl-token
            - name: SL_BUILD_SESSION_ID
              value: "build-session-id-placeholder" # Replaced by workflow
            - name: SL_APP_NAME
              value: "app-name-placeholder" # Replaced by workflow
            - name: SL_BRANCH_NAME
              value: "branch-name-placeholder" # Replaced by workflow
            - name: SL_ENVIRONMENT
              value: "environment-placeholder" # Replaced by workflow
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/app/sealights/sl-test-listener.jar=token=$(SL_TOKEN),buildSessionId=$(SL_BUILD_SESSION_ID),appName=$(SL_APP_NAME),branchName=$(SL_BRANCH_NAME),environment=$(SL_ENVIRONMENT)"
---
apiVersion: v1
kind: Service
metadata:
  name: sp-demo-java-app-service
spec:
  selector:
    app: sp-demo-java-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer