name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    needs: [package, unit-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Set up gcloud CLI
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Install gke-gcloud-auth-plugin
      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gke-gcloud-auth-plugin --version

      # Debug: List GKE Clusters
      - name: List GKE Clusters
        run: |
          gcloud container clusters list --region us-central1

      # Get GKE credentials
      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials sp-demo-java-app-cluster --region us-central1 --project ${{ secrets.GCP_PROJECT_ID }}

      # Deploy to GKE
      - name: Deploy to GKE
        run: |
          sed -i "s|tag-placeholder|${{ github.sha }}|g" k8s/deployment.yaml
          kubectl apply -f k8s/deployment.yaml

      # Get Service External IP
      - name: Get Service External IP
        run: |
          echo "Waiting for external IP to be assigned..."
          for i in {1..12}; do
            EXTERNAL_IP=$(kubectl get svc sp-demo-java-app-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
            if [ -n "$EXTERNAL_IP" ]; then
              echo "App is accessible at: http://$EXTERNAL_IP"
              break
            fi
            echo "External IP not yet assigned, waiting 10 seconds..."
            sleep 10
          done
          if [ -z "$EXTERNAL_IP" ]; then
            echo "Error: Could not get external IP after 2 minutes."
            exit 1
          fi