name: SonarCloud Analysis
on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    name: Build and Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for SonarCloud to analyze history
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21' # Updated to match project's Java version
          distribution: 'temurin'
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Build with Gradle and generate JaCoCo reports
        run: ./gradlew build jacocoTestReport jacocoIntegrationTestReport jacocoAggregatedReport --info
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            build/reports/jacoco/
            build/classes/
            build/tmp/
          retention-days: 1

  analyze:
    name: Analyze with SonarCloud
    needs: build
    runs-on: ubuntu-latest
    # This environment requires approval before the job runs
    # To set up required reviewers:
    # 1. Go to repository Settings > Environments
    # 2. Create a new environment named "sonar-approval"
    # 3. Enable "Required reviewers" and add the GitHub users who can approve
    environment:
      name: sonar-approval
      url: https://sonarcloud.io/dashboard?id=sperezintexas_sp-demo-java-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build/
      - name: Analyze with SonarQube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar --info -Dsonar.projectKey=sperezintexas_sp-demo-java-app -Dsonar.organization=sperezintexas -Dsonar.host.url=https://sonarcloud.io -Dsonar.gradle.skipCompile=true -Dsonar.token=${SONAR_TOKEN}
